const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST'
const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS'
const ITEM_LIST_FAILURE = 'ITEM_LIST_FAILURE'

const ITEM_DETAILS_REQUEST = 'ITEM_DETAIlS_REQUEST'
const ITEM_DETAILS_SUCCESS = 'ITEM_DETAIlS_SUCCESS'
const ITEM_DETAILS_FAILURE = 'ITEM_DETAIlS_FAILURE'

export {
    ITEM_LIST_REQUEST,
    ITEM_LIST_SUCCESS,
    ITEM_LIST_FAILURE,
    ITEM_DETAILS_REQUEST,
    ITEM_DETAILS_SUCCESS,
    ITEM_DETAILS_FAILURE
}